### PR TITLE
Pylint 2.12

### PR DESCRIPTION
**Pull request by stanislavlevin**
disabled:
- `consider-using-f-string`
- `redundant-u-string-prefix`
- `use-dict-literal`
- `unspecified-encoding`
- `use-list-literal`

enabled:
- `useless-suppression`

Fixes: https://github.com/freeipa/freeipa-healthcheck/issues/244

### CODE REVIEW

**Comment by rcritten** [comment]
Thanks for this considerable patch. The changes look valid to me, I just find some of the new linting to be annoying :-)

Particularly the open() with encoding. Is that really necessary? I'm not really the best to judge this as I'm English-only whose alphabet consists only in ASCII so I may have lucked out in the encoding assumptions. Is my assumption correct that we're only dealing with plain ASCII or is it just safer/defensive programming to be explicit about it? Can we safely ignore this instead of extending the open arguments?

**Comment by stanislavlevin** [comment]
Another point is waiting for updated `pylintrc` in freeipa (I will open PR in a day or two) since `pylintrc` was force replaced with freeipa's one and thereby healthcheck inherits many skipped checks :(

**Comment by rcritten** [comment]
I had read the PEP which led me to the question. It didn't really clarify things as you have. I'm ok with this. I'll hold off for your further pylint changes.

And yeah, honestly, you know pylint way better than I do hence the copying from a working, similar project.

**Comment by stanislavlevin** [comment]
I synced to freeipa configuration, most of the new checkers have been skipped.

**Comment by rcritten** [comment]
Just to make sure I understand, this is synced to freeipa PR https://github.com/freeipa/freeipa/pull/6196 ?

**Comment by stanislavlevin** [comment]
let me recheck please.

**Comment by stanislavlevin** [comment]
@rcritten, added 3 more commits to sync `pylint_plugins.py` and `pylintrc`. Now they are exactly the same as IPA's ones in today's `dev` branch.

**Comment by rcritten** [comment]
Sorry for the delay, been buried with work. I'll try to get to this soon. A quick look turned up no issues.

**Comment by rcritten** [comment]
LGTM, thanks for the contribution!

**Comment by stanislavlevin** [comment]
@rcritten, thank you!

**Pull request merged**
