### PR TITLE
ipa-idns: Handle AAAA RRs

### PR DESCRIPTION
**Pull request by stanislavlevin**
Fixes: https://github.com/freeipa/freeipa-healthcheck/issues/135

### CODE REVIEW

**Comment by rcritten** [comment]
This looks good, thanks. Any chance you could add AAAA support to tests/test_ipa_dns.py ?

**Comment by stanislavlevin** [comment]
Sure, I'll check.

**Comment by stanislavlevin** [comment]
Updated.

**Comment by rcritten** [comment]
Perfect, thanks!

**Pull request merged**
