### PR TITLE
Include newline in JSON output

### PR DESCRIPTION
**Pull request by rcritten**
This prettifies the output, particularly when going to stdout

https://github.com/freeipa/freeipa-healthcheck/issues/36

### CODE REVIEW

**Comment by fcami** [comment]
Hi @rcritten thanks for the PR - would you mind making that conditional on terminal usage too using sys.stdout.isatty()?

**Comment by rcritten** [comment]
done

**Comment by fcami** [comment]
hi @rcritten could you please rebase now that master includes the travis fix?

**Comment by rcritten** [comment]
rebased

**Comment by fcami** [comment]
This indeed makes the terminal runs more readable but does not change the log format. ACK.

**Pull request merged**
